"""Generate /fonts/fonts.css from font files on disk.

Emits WOFF2-first @font-face rules (with OTF as fallback) so visitors get
the smallest possible download. Run convert_to_woff2.py first to produce
the .woff2 files.

Google Fonts (CJK + Latin fallbacks) are loaded in a separate
google-fonts.css so ad-blockers that kill *.googleapis.com don't take out
all our locally-hosted fonts too.

Run as part of vps-post-deploy.sh AFTER fonts are present on disk:
    python3 build_fonts_css.py /var/www/kylepounds.org/fonts
"""
import os
import sys
from urllib.parse import quote

# Separate file so ad-blocker hits don't kill local fonts
GOOGLE_IMPORT = (
    "@import url('https://fonts.googleapis.com/css2"
    "?family=Nanum+Myeongjo&family=Noto+Sans+JP&family=Noto+Sans+KR"
    "&family=Noto+Sans+Thai&family=Libre+Baskerville&family=Cabin"
    "&display=swap');"
)


def font_family_from_filename(fname: str) -> str:
    for ext in (".woff2", ".otf", ".ttf"):
        if fname.lower().endswith(ext):
            return fname[: -len(ext)].strip()
    return fname.strip()


def build_css(fonts_dir: str) -> str:
    if not os.path.isdir(fonts_dir):
        raise SystemExit(f"fonts dir not found: {fonts_dir}")

    files = os.listdir(fonts_dir)
    woff2_names = {f[:-6] for f in files if f.lower().endswith(".woff2")}

    out: list[str] = []
    out.append("/* Kyle Pounce — Auto-generated by build_fonts_css.py */")
    out.append("/* DO NOT EDIT — re-run the script if font files change.  */")
    out.append("")
    # Windows CJK local-only fallbacks
    out.append("@font-face { font-family: 'GungsuhChe'; src: local('GungsuhChe'), local('Gungsuh'); }")
    out.append("@font-face { font-family: 'Gungsuh';    src: local('Gungsuh'); }")
    out.append("")

    # Prefer WOFF2 sources; fall back to OTF if no WOFF2 sibling exists
    seen_families: set[str] = set()
    otf_files = sorted(f for f in files if f.lower().endswith(".otf"))

    for fname in otf_files:
        family = font_family_from_filename(fname)
        if family in seen_families:
            continue
        seen_families.add(family)

        stem = fname[:-4]  # filename without .otf
        has_woff2 = stem in woff2_names

        if has_woff2:
            woff2_url = "/fonts/" + quote(stem + ".woff2")
            otf_url   = "/fonts/" + quote(fname)
            src = (
                f"local({family!r}),\n"
                f"    url('{woff2_url}') format('woff2'),\n"
                f"    url('{otf_url}') format('opentype')"
            )
        else:
            otf_url = "/fonts/" + quote(fname)
            src = f"local({family!r}), url('{otf_url}') format('opentype')"

        out.append(
            f"@font-face {{\n"
            f"  font-family: {family!r};\n"
            f"  src: {src};\n"
            f"  font-display: swap;\n"
            f"}}"
        )

    out.append("")
    out.append(f"/* {len(seen_families)} @font-face rules emitted */")
    return "\n".join(out) + "\n"


def build_google_css() -> str:
    return f"{GOOGLE_IMPORT}\n/* Auto-generated — ad-blocker safe separation from local fonts */\n"


def main() -> None:
    fonts_dir = sys.argv[1] if len(sys.argv) > 1 else "/var/www/kylepounds.org/fonts"
    css = build_css(fonts_dir)
    out_path = os.path.join(fonts_dir, "fonts.css")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(css)

    google_path = os.path.join(fonts_dir, "google-fonts.css")
    with open(google_path, "w", encoding="utf-8") as f:
        f.write(build_google_css())

    rule_count = css.count("@font-face")
    print(f"Wrote {out_path} ({rule_count} @font-face rules) + {google_path}")


if __name__ == "__main__":
    main()
