"""Generate /fonts/fonts.css from the actual .otf files on disk.

Why this script exists: the original fonts.css was hand-crafted with
double-extension paths like 'Rosella Deco.otf.otf' that don't match the
real files. Every @font-face rule failed, so visitors saw browser fallback
fonts instead of Kyle's intended Adobe fonts.

Run as part of mirror-and-deploy.sh AFTER fonts are present on disk:
    python3 build_fonts_css.py /var/www/kylepounds.org/fonts
"""
import os
import sys
from urllib.parse import quote

# Google Fonts fallbacks for non-Latin scripts Kyle's CSS references.
GOOGLE_IMPORT = (
    "@import url('https://fonts.googleapis.com/css2"
    "?family=Nanum+Myeongjo&family=Noto+Sans+JP&family=Noto+Sans+KR"
    "&family=Noto+Sans+Thai&family=Libre+Baskerville&family=Cabin"
    "&display=swap');"
)


def font_family_from_filename(fname: str) -> str:
    """Strip .otf and use the rest as the font-family name (preserving spaces)."""
    name = fname
    if name.lower().endswith(".otf"):
        name = name[:-4]
    return name.strip()


def build_css(fonts_dir: str) -> str:
    if not os.path.isdir(fonts_dir):
        raise SystemExit(f"fonts dir not found: {fonts_dir}")

    out: list[str] = []
    out.append("/* Kyle Pounce — Auto-generated by build_fonts_css.py */")
    out.append("/* DO NOT EDIT — re-run the script if .otf files change. */")
    out.append("")
    out.append(GOOGLE_IMPORT)
    out.append("")
    # Windows font substitutes — try local first, fall back to similar shipped fonts.
    out.append("@font-face { font-family: 'GungsuhChe'; src: local('GungsuhChe'), local('Gungsuh'); }")
    out.append("@font-face { font-family: 'Gungsuh';    src: local('Gungsuh'); }")
    out.append("")

    fonts = sorted(f for f in os.listdir(fonts_dir) if f.lower().endswith(".otf"))
    for fname in fonts:
        family = font_family_from_filename(fname)
        # `local()` first so users who own the Adobe font use their copy;
        # `url()` second is the hosted fallback. quote() escapes spaces to %20
        # but leaves slashes alone.
        url = "/fonts/" + quote(fname)
        out.append(
            f"@font-face {{\n"
            f"  font-family: {family!r};\n"
            f"  src: local({family!r}), url('{url}') format('opentype');\n"
            f"  font-display: swap;\n"
            f"}}"
        )

    out.append("")
    out.append(f"/* {len(fonts)} @font-face rules emitted */")
    return "\n".join(out) + "\n"


def main() -> None:
    fonts_dir = sys.argv[1] if len(sys.argv) > 1 else "/var/www/kylepounds.org/fonts"
    css = build_css(fonts_dir)
    out_path = os.path.join(fonts_dir, "fonts.css")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(css)
    rule_count = css.count("@font-face")
    print(f"Wrote {out_path} — {rule_count} @font-face rules")


if __name__ == "__main__":
    main()
